function y = cheb1_test(x)
%CHEB1_TEST Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1.
% Generated on: 13-Dec-2015 12:08:18

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass1 = 1400;   % First Passband Frequency
    % Fstop1 = 1600;   % First Stopband Frequency
    % Fstop2 = 1700;   % Second Stopband Frequency
    % Fpass2 = 1900;   % Second Passband Frequency
    % Apass1 = 0.5;    % First Passband Ripple (dB)
    % Astop  = 100;    % Stopband Attenuation (dB)
    % Apass2 = 1;      % Second Passband Ripple (dB)
    % Fs     = 11025;  % Sampling Frequency
    %
    % h = fdesign.bandstop('fp1,fst1,fst2,fp2,ap1,ast,ap2', Fpass1, Fstop1, ...
    %                      Fstop2, Fpass2, Apass1, Astop, Apass2, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'MatchExactly', 'stopband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -1.19109457724896 1 1 -0.944149011850109 ...
        0.973798414849296; 1 -1.19109457724896 1 1 -1.36887580249377 ...
        0.978408201077349; 1 -1.19109457724896 1 1 -0.874167408701267 ...
        0.898973788280301; 1 -1.19109457724896 1 1 -1.3500293652318 ...
        0.918326777233549; 1 -1.19109457724896 1 1 -1.28067939458272 ...
        0.777152115990144; 1 -1.19109457724896 1 1 -0.744444676222408 ...
        0.719633757020691; 1 -1.19109457724896 1 1 -0.899161809643456 ...
        0.509807578370859], ...
        'ScaleValues', [0.979366707361909; 0.979366707361909; ...
        0.943432867998684; 0.943432867998684; 0.860189949036155; ...
        0.860189949036155; 0.754903789185429; 1]);
end

s = double(x);
y = step(Hd,s);
y=y./max(abs(y));
audiowrite('clean_Cheb1.wav',y,11025);